version: "3"
services:
  app:
    container_name: app
    build: ./infra/php
    volumes:
      - ./infra/php/php.ini:/usr/local/etc/php/php.ini
      - ./src:/var/www/exercise-app
    ports:
      - 8080:80
  db:
    container_name: db
    build: ./infra/mysql
    volumes:
      - ./infra/mysql:/var/lib/mysql
    ports:
      - 33060:3306
